# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: NationalSecurityAgency.Ghidra
PackageVersion: 10.3.3
PackageLocale: en-US
Publisher: National Security Agency
PublisherUrl: https://www.nsa.gov/
PackageName: Ghidra
PackageUrl: https://ghidra-sre.org/
License: Apache-2.0
LicenseUrl: https://github.com/NationalSecurityAgency/ghidra/blob/master/LICENSE
ShortDescription: Ghidra is a software reverse engineering (SRE) framework
Description: |-
  Ghidra is a software reverse engineering (SRE) framework created and maintained by the National Security Agency Research Directorate.
  This framework includes a suite of full-featured, high-end software analysis tools
  that enable users to analyze compiled code on a variety of platforms including Windows, macOS, and Linux.
  Capabilities include disassembly, assembly, decompilation, graphing, and scripting, along with hundreds of other features.
  Ghidra supports a wide variety of processor instruction sets and executable formats and can be run in both user-interactive and automated modes.
  Users may also develop their own Ghidra extension components and/or scripts using Java or Python.
Tags:
- reverse-engineering
- disassembler
- debugger
- static-analysis
ReleaseNotesUrl: https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.3.3_build/Ghidra/Configurations/Public_Release/src/global/docs/WhatsNew.html
ManifestType: defaultLocale
ManifestVersion: 1.4.0
