# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: NationalSecurityAgency.Ghidra
PackageVersion: 10.3.3
InstallerType: zip
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.OpenJDK.17
ReleaseDate: 2023-08-30
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ghidra_10.3.3_PUBLIC\ghidraRun.bat
    PortableCommandAlias: ghidra
  InstallerUrl: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.3_build/ghidra_10.3.3_PUBLIC_20230829.zip
  InstallerSha256: 63833361bea8ef5ada1bc28cd2aa2ae4ab43204d2672b595500372582152eebe
ManifestType: installer
ManifestVersion: 1.4.0
